version: '3.4'

services:
  db:
    image: mysql:8.0
    volumes:
      - database:/var/lib/mysql
      - ./init/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'

volumes:
  database:
